name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: googleapis/release-please-action@v4
        with:
          draft-pull-request: true
          package-name: critical-es-value
          release-type: python
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

